# Imports

In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline
import pandas as pd
import numpy as np
import anndata as ad
import scanpy as sc
import pandas as pd
from ciim.src.utils.util import base_dir

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.max_colwidth', None)

# soundlife cohort
96 subjects (donors), 49 young and 47 old
each subject has multiple samples (~10) -> what these samples stand for?

<img src="downloads/image1.png" width="50%">
<img src="downloads/image2.png" width="50%">

In [8]:
adata = ad.read_h5ad(f'{base_dir}/datasets/bulk/soundlife_bulk.h5ad', backed='r')
#TODO: Flu Year 3 Stand-Alone should be vaccinated negative 
adata.obs[adata.obs['subject.subjectGuid']=='BR2036'][['condition','sample.visitName', 'subject.bmi', 'subject.ageAtFirstDraw', 'sample.subjectAgeAtDraw', 'vaccinated', 'followup_year', 'followup_day']].drop_duplicates(keep='first').sort_values('sample.visitName')

   condition         sample.visitName  subject.bmi  subject.ageAtFirstDraw  sample.subjectAgeAtDraw  vaccinated  followup_year  followup_day
61   healthy         Flu Year 1 Day 0         23.0                      56                       56        True              1             0
62   healthy         Flu Year 1 Day 7         23.0                      56                       56        True              1             7
63   healthy        Flu Year 1 Day 90         23.0                      56                       57        True              1            90
64   healthy         Flu Year 2 Day 0         23.0                      56                       57        True              2             0
65   healthy         Flu Year 2 Day 7         23.0                      56                       57        True              2             7
66   healthy        Flu Year 2 Day 90         23.0                      56                       58        True              2            90
67   healthy   Flu Year 3 Stand-Alone         23.0                      56                       58        True              3          <NA>
68   healthy   Immune Variation Day 0         23.0                      56                       57       False           <NA>             0
69   healthy   Immune Variation Day 7         23.0                      56                       57       False           <NA>             7
70   healthy  Immune Variation Day 90         23.0                      56                       57       False           <NA>            90

In [5]:
adata.obs['visit_explanations'].unique()

['Pre-vaccination baseline before first annual flu shot (fall 2019-2020 season).', 'Peak immune response 7 days after first flu vaccination, capturing B cell activation and antibody production.', 'Memory phase ~3 months after first vaccination, assessing antibody durability and long-term immune memory.', 'Pre-vaccination baseline before second annual flu shot (fall 2020-2021 season), testing reproducibility.', 'Peak immune response 7 days after second flu vaccination, confirming consistent age-related defects across seasons.', ..., NaN, 'Baseline measurement without vaccination challenge, assessing natural immune state and variation.', 'Follow-up 7 days later without vaccination, distinguishing natural variation from vaccine-induced changes.', 'Long-term monitoring ~3 months later without vaccination, confirming stable age-related signatures independent of perturbation.', 'Additional monitoring visit outside the main 2-year study protocol, not part of primary vaccination analysis.']
Length: 11
Categories (10, object): ['Additional monitoring visit outside the main 2-year study protocol, not part of primary vaccination analysis.', 'Baseline measurement without vaccination challenge, assessing natural immune state and variation.', 'Follow-up 7 days later without vaccination, distinguishing natural variation from vaccine-induced changes.', 'Long-term monitoring ~3 months later without vaccination, confirming stable age-related signatures independent of perturbation.', ..., 'Peak immune response 7 days after first flu vaccination, capturing B cell activation and antibody production.', 'Peak immune response 7 days after second flu vaccination, confirming consistent age-related defects across seasons.', 'Pre-vaccination baseline before first annual flu shot (fall 2019-2020 season).', 'Pre-vaccination baseline before second annual flu shot (fall 2020-2021 season), testing reproducibility.']

In [12]:
# TODO: make umap plot colored by cell type and disease
# sc.pp.neighbors(adata)
# sc.tl.umap(adata)
# sc.pl.umap(adata[adata.obs['cell_type']=='CD8T'], color=['cell_type', 'condition'])

In [2]:
adata = ad.read_h5ad('downloads/SoundLife_OlderAdult_Female_CMVneg.h5ad', backed='r')
obs = adata.obs

In [ ]:
obs[['barcodes', 'sample.subjectAgeAtDraw', 'sample.subjectGuid', 'batch_id', 'pool_id', 'well_id', 'chip_id', 'cohort.cohortGuid', 'subject.cmv', 'subject.bmi	', 'subject.race', 'subject.ethnicity']].head()

,barcodes,original_barcodes,cell_name,batch_id,pool_id,chip_id,well_id,n_genes,n_reads,n_umis,total_counts_mito,pct_counts_mito,doublet_score,predicted_AIFI_L1,AIFI_L1_score,AIFI_L1,predicted_AIFI_L2,AIFI_L2_score,AIFI_L2,predicted_AIFI_L3,AIFI_L3_score,AIFI_L3,sample.sampleKitGuid,cohort.cohortGuid,subject.subjectGuid,subject.biologicalSex,subject.cmv,subject.bmi,subject.race,subject.ethnicity,subject.birthYear,subject.ageAtFirstDraw,sample.visitName,sample.drawYear,sample.subjectAgeAtDraw,specimen.specimenGuid,pipeline.fileGuid,subject.ageGroup,vaccine_year
barcodes,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2c1bccbcbe4211eb98a80ea06e750864,2c1bccbcbe4211eb98a80ea06e750864,GTCCTCATCTCACGAA,waterborne_disparaged_pilchard,B055,B055-P1,B055-P1C1,B055-P1C1W1,1762,8509,4380,229,5.228311,0.121912,T cell,0.999997,T cell,Memory CD8 T cell,0.592773,Memory CD4 T cell,GZMB- CD27+ EM CD4 T cell,1.000000,GZMB- CD27+ EM CD4 T cell,KT01414,BR2,BR2036,Female,Negative,23.0,Caucasian,Non-Hispanic origin,1964,56,Flu Year 1 Day 90,2021,57,PB01414-01,33e58048-86b3-482c-b003-4aeafc98cd4c,Sound Life Older Adult,2020-2021
2c2aede6be4211eb98a80ea06e750864,2c2aede6be4211eb98a80ea06e750864,TGATTTCAGTCTGGAG,quixotic_regainable_reindeer,B055,B055-P1,B055-P1C1,B055-P1C1W1,1060,5921,3061,223,7.285201,0.055901,T cell,0.999996,T cell,Memory CD8 T cell,0.225684,Memory CD4 T cell,GZMB- CD27+ EM CD4 T cell,1.000000,GZMB- CD27+ EM CD4 T cell,KT01414,BR2,BR2036,Female,Negative,23.0,Caucasian,Non-Hispanic origin,1964,56,Flu Year 1 Day 90,2021,57,PB01414-01,33e58048-86b3-482c-b003-4aeafc98cd4c,Sound Life Older Adult,2020-2021
f59e3182be3911ebaf013a021f53d0ed,f59e3182be3911ebaf013a021f53d0ed,CGGAACCCAGAACTTC,malcontent_voguish_grackle,B055,B055-P1,B055-P1C1,B055-P1C1W4,948,4138,2150,181,8.418605,0.064961,T cell,0.999137,T cell,Memory CD8 T cell,0.804685,Memory CD4 T cell,GZMB- CD27+ EM CD4 T cell,1.000000,GZMB- CD27+ EM CD4 T cell,KT01414,BR2,BR2036,Female,Negative,23.0,Caucasian,Non-Hispanic origin,1964,56,Flu Year 1 Day 90,2021,57,PB01414-01,33e58048-86b3-482c-b003-4aeafc98cd4c,Sound Life Older Adult,2020-2021
f5b2122ebe3911ebaf013a021f53d0ed,f5b2122ebe3911ebaf013a021f53d0ed,GTTACAGGTATCACGT,dour_nosophobic_hammerkop,B055,B055-P1,B055-P1C1,B055-P1C1W4,1739,9025,4816,197,4.090532,0.096433,T cell,0.999999,T cell,Memory CD8 T cell,0.831006,Memory CD4 T cell,GZMB- CD27+ EM CD4 T cell,1.000000,GZMB- CD27+ EM CD4 T cell,KT01414,BR2,BR2036,Female,Negative,23.0,Caucasian,Non-Hispanic origin,1964,56,Flu Year 1 Day 90,2021,57,PB01414-01,33e58048-86b3-482c-b003-4aeafc98cd4c,Sound Life Older Adult,2020-2021
f5b9780cbe3911ebaf013a021f53d0ed,f5b9780cbe3911ebaf013a021f53d0ed,TCCGGGATCGACGAGA,florid_jaunty_dorado,B055,B055-P1,B055-P1C1,B055-P1C1W4,1453,6582,3388,256,7.556080,0.057285,T cell,0.999575,T cell,Memory CD8 T cell,0.046352,Memory CD4 T cell,GZMB- CD27+ EM CD4 T cell,0.999997,GZMB- CD27+ EM CD4 T cell,KT01414,BR2,BR2036,Female,Negative,23.0,Caucasian,Non-Hispanic origin,1964,56,Flu Year 1 Day 90,2021,57,PB01414-01,33e58048-86b3-482c-b003-4aeafc98cd4c,Sound Life Older Adult,2020-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13119f0299c911ee89d90ef72a6b8a31,13119f0299c911ee89d90ef72a6b8a31,CATTCTAGTGGACTGA,paranoiac_coaly_ankole,B109,B109-P2,B109-P2C3,B109-P2C3W3,2235,35132,9266,92,0.992877,0.081748,Progenitor cell,0.999999,Progenitor cell,Progenitor cell,1.000000,Progenitor cell,CMP cell,1.000000,CMP cell,KT02464,BR2,BR2034,Female,Negative,25.0,Caucasian,Non-Hispanic origin,1957,63,Flu Year 2 Day 0,2021,64,PB02464-001,c1ee115b-b363-462e-92bf-576b5993e029,Sound Life Older Adult,2021-2022
131e5ef499c911ee89d90ef72a6b8a31,131e5ef499c911ee89d90ef72a6b8a31,TATTGGGGTCTAGGTT,fraternal_unhealthy_woodpecker,B109,B109-P2,B109-P2C3,B109-P2C3W3,1293,17771,5251,2,0.038088,0.104218,Progenitor cell,0.899549,Progenitor cell,Progenitor cell,0.999351,Progenitor cell,CMP cell,1.000000,CMP cell,KT02464,BR2,BR2034,Female,Negative,25.0,Caucasian,Non-Hispanic origin,1957,63,Flu Year 2 Day 0,2021,64,PB02464-001,c1ee115b-b363-462e-92bf-576b5993e029,Sound Life Older Adult,2021-2022
8a92a67e99ca11ee89524629b1cc3bb1,8a92a67e99ca11ee89524629b1cc3bb1,AGATCCATCGTGGCTG,churchly_lucky_halibut,B109,B109-P2,B109-P2C3,B109-P2C3W4,3045,57110,15278,77,0.503993,0.061532,Progenitor cell,0.999999,Progenitor cell,Progenitor cell,1.000000,Progenitor cell,CMP cell,1.000000,CMP cell,KT02464,BR2,BR2034,Female,Negative,25.0,Caucasian,Non-Hispanic origin,1957,63,Flu Year 2 Day 0,2021,64,PB02464-001,c1ee115b-b363-462e-92bf-576b5993e029,Sound Life Older Adult,2021-2022
01e238ca99bc11eeb61a8ae2855d8650,01e238ca99bc11eeb61a8ae2855d8650,GTCGCGAGTTCAATCG,hogged_aquamarine_kodiakbear,B109,B109-P2,B109-P2C3,B109-P2C3W5,2795,39567,14377,195,1.356333,0.047653,Progenitor cell,1.000000,Progenitor cell,Progenitor cell,1.000000,Progenitor cell,CMP cell,1.000000,CMP cell,KT02464,BR2,BR2034,Female,Negative,25.0,Caucasian,Non-Hispanic origin,1957,63,Flu Year 2 Day 0,2021,64,PB02464-001,c1ee115b-b363-462e-92bf-576b5993e029,Sound Life Older Adult,2021-2022
01e6aaa499bc11eeb61a8ae2855d8650,01e6aaa499bc11eeb61a8ae2855d8650,TCGCAGGTCCACAGCG,snowcapped_crucial_squid,B109,B109-P2,B109-P2C3,B109-P2C3W5,2558,36297,10618,116,1.092484,0.065847,Progenitor cell,1.000000,Progenitor cell,Progenitor cell,1.000000,Progenitor cell,CMP cell,1.000000,CMP cell,KT02464,BR2,BR2034,Female,Negative,25.0,Caucasian,Non-Hispanic origin,1957,63,Flu Year 2 Day 0,2021,64,PB02464-001,c1ee115b-b363-462e-92bf-576b5993e029,Sound Life Older Adult,2021-2022

                                         sample.visitName  subject.bmi  subject.ageAtFirstDraw  sample.subjectAgeAtDraw
barcodes
5ec5d62223db11ec8fb6d64cd9da18b7         Flu Year 1 Day 0         23.0                      56                       56
b255fe9ae8ba11eb951c4a933a1ddc30         Flu Year 1 Day 7         23.0                      56                       56
2c1bccbcbe4211eb98a80ea06e750864        Flu Year 1 Day 90         23.0                      56                       57
15e1ac26965211ecbf329a5ba518ef1a         Flu Year 2 Day 0         23.0                      56                       57
15dc2cf6965211ecbf329a5ba518ef1a         Flu Year 2 Day 7         23.0                      56                       57
a3d43e8cd52a11edb701e233a95dd86a        Flu Year 2 Day 90         23.0                      56                       58
3fd704146ffd11ee833f960f38b040be   Flu Year 3 Stand-Alone         23.0                      56                       58
5bb45fd620a911ee8fef66c3e3d85ce1   Immune Variation Day 0         23.0                      56                       57
8fde5dc8c09011eb909cd6ff17e70a6b   Immune Variation Day 7         23.0                      56                       57
49c5e2b6967111ee982ffe26c95e21bc  Immune Variation Day 90         23.0                      56                       57

In [7]:
adata = ad.read_h5ad('/vol/projects/jnourisa/datasets/bulk/parsebioscience_bulk.h5ad', backed='r')
adata

AnnData object with n_obs × n_vars = 5760 × 34285 backed at '/vol/projects/jnourisa/datasets/bulk/parsebioscience_bulk.h5ad'
    obs: 'sum_by', 'age', 'cell_type', 'is_control', 'perturbation_type', 'well', 'donor_id', 'perturbation', 'cell_count'
    uns: 'data_reference', 'data_url', 'dataset_description', 'dataset_id', 'dataset_name', 'dataset_organism', 'dataset_summary', 'normalization_id'
    layers: 'lognorm'

In [21]:
adata.obs[['cell_type', 'perturbation', 'donor_id', 'well']].drop_duplicates()

      cell_type perturbation donor_id well
0             B       4-1BBL  Donor10   H5
1             B       4-1BBL  Donor11   H5
2             B       4-1BBL  Donor12   H5
3             B       4-1BBL   Donor1   H5
4             B       4-1BBL   Donor2   H5
...         ...          ...      ...  ...
12621        NK         VEGF   Donor4   F1
12622        NK         VEGF   Donor5   F1
12623        NK         VEGF   Donor6   F1
12624        NK         VEGF   Donor7   F1
12626        NK         VEGF   Donor9   F1

[5760 rows x 4 columns]

In [17]:
adata[(adata.obs['is_control'])&(adata.obs['cell_type']=='CD4T')&(adata.obs['donor_id']=='Donor10')].obs

                            sum_by cell_type perturbation                       group well cell_type_minor donor_id  is_control perturbation_type  cell_count  age
5542   _CD4 Memory_PBS_Donor10_H10      CD4T          PBS  CD4 Memory_PBS_Donor10_H10  H10      CD4 Memory  Donor10        True          cytokine        1088   42
5543   _CD4 Memory_PBS_Donor10_H11      CD4T          PBS  CD4 Memory_PBS_Donor10_H11  H11      CD4 Memory  Donor10        True          cytokine        1107   42
5544   _CD4 Memory_PBS_Donor10_H12      CD4T          PBS  CD4 Memory_PBS_Donor10_H12  H12      CD4 Memory  Donor10        True          cytokine         840   42
5545    _CD4 Memory_PBS_Donor10_H7      CD4T          PBS   CD4 Memory_PBS_Donor10_H7   H7      CD4 Memory  Donor10        True          cytokine         926   42
5546    _CD4 Memory_PBS_Donor10_H8      CD4T          PBS   CD4 Memory_PBS_Donor10_H8   H8      CD4 Memory  Donor10        True          cytokine        1028   42
5547    _CD4 Memory_PBS_Donor10_H9      CD4T          PBS   CD4 Memory_PBS_Donor10_H9   H9      CD4 Memory  Donor10        True          cytokine         903   42
6694    _CD4 Naive_PBS_Donor10_H10      CD4T          PBS   CD4 Naive_PBS_Donor10_H10  H10       CD4 Naive  Donor10        True          cytokine         552   42
6695    _CD4 Naive_PBS_Donor10_H11      CD4T          PBS   CD4 Naive_PBS_Donor10_H11  H11       CD4 Naive  Donor10        True          cytokine         639   42
6696    _CD4 Naive_PBS_Donor10_H12      CD4T          PBS   CD4 Naive_PBS_Donor10_H12  H12       CD4 Naive  Donor10        True          cytokine         519   42
6697     _CD4 Naive_PBS_Donor10_H7      CD4T          PBS    CD4 Naive_PBS_Donor10_H7   H7       CD4 Naive  Donor10        True          cytokine         792   42
6698     _CD4 Naive_PBS_Donor10_H8      CD4T          PBS    CD4 Naive_PBS_Donor10_H8   H8       CD4 Naive  Donor10        True          cytokine         787   42
6699     _CD4 Naive_PBS_Donor10_H9      CD4T          PBS    CD4 Naive_PBS_Donor10_H9   H9       CD4 Naive  Donor10        True          cytokine         763   42
16915        _Treg_PBS_Donor10_H10      CD4T          PBS        Treg_PBS_Donor10_H10  H10            Treg  Donor10        True          cytokine          60   42
16916        _Treg_PBS_Donor10_H11      CD4T          PBS        Treg_PBS_Donor10_H11  H11            Treg  Donor10        True          cytokine          66   42
16917        _Treg_PBS_Donor10_H12      CD4T          PBS        Treg_PBS_Donor10_H12  H12            Treg  Donor10        True          cytokine          50   42
16918         _Treg_PBS_Donor10_H7      CD4T          PBS         Treg_PBS_Donor10_H7   H7            Treg  Donor10        True          cytokine          69   42
16919         _Treg_PBS_Donor10_H8      CD4T          PBS         Treg_PBS_Donor10_H8   H8            Treg  Donor10        True          cytokine          68   42
16920         _Treg_PBS_Donor10_H9      CD4T          PBS         Treg_PBS_Donor10_H9   H9            Treg  Donor10        True          cytokine          74   42

In [10]:
# Create age mapping from the donor information
donor_age_map = {
    'Donor1': 75,
    'Donor2': 34,
    'Donor3': 68,
    'Donor4': 59,
    'Donor5': 41,
    'Donor6': 38,
    'Donor7': 45,
    'Donor8': 52,
    'Donor9': 38,
    'Donor10': 42,
    'Donor11': 46,
    'Donor12': 36
}

# Map the age to obs based on donor_id
adata.obs['age'] = adata.obs['donor_id'].map(donor_age_map)
adata.obs

                                         sum_by cell_type perturbation                                    group well        cell_type_minor donor_id  is_control perturbation_type  cell_count  age
0      _B Intermediate/Memory_4-1BBL_Donor10_H5         B       4-1BBL  B Intermediate/Memory_4-1BBL_Donor10_H5   H5  B Intermediate/Memory  Donor10       False          cytokine         176   42
1      _B Intermediate/Memory_4-1BBL_Donor11_H5         B       4-1BBL  B Intermediate/Memory_4-1BBL_Donor11_H5   H5  B Intermediate/Memory  Donor11       False          cytokine         213   46
2      _B Intermediate/Memory_4-1BBL_Donor12_H5         B       4-1BBL  B Intermediate/Memory_4-1BBL_Donor12_H5   H5  B Intermediate/Memory  Donor12       False          cytokine         247   36
3       _B Intermediate/Memory_4-1BBL_Donor1_H5         B       4-1BBL   B Intermediate/Memory_4-1BBL_Donor1_H5   H5  B Intermediate/Memory   Donor1       False          cytokine         294   75
4       _B Intermediate/Memory_4-1BBL_Donor2_H5         B       4-1BBL   B Intermediate/Memory_4-1BBL_Donor2_H5   H5  B Intermediate/Memory   Donor2       False          cytokine         469   34
...                                         ...       ...          ...                                      ...  ...                    ...      ...         ...               ...         ...  ...
17126                      _Treg_VEGF_Donor5_F1      CD4T         VEGF                      Treg_VEGF_Donor5_F1   F1                   Treg   Donor5       False          cytokine         123   41
17127                      _Treg_VEGF_Donor6_F1      CD4T         VEGF                      Treg_VEGF_Donor6_F1   F1                   Treg   Donor6       False          cytokine         281   38
17128                      _Treg_VEGF_Donor7_F1      CD4T         VEGF                      Treg_VEGF_Donor7_F1   F1                   Treg   Donor7       False          cytokine         266   45
17129                      _Treg_VEGF_Donor8_F1      CD4T         VEGF                      Treg_VEGF_Donor8_F1   F1                   Treg   Donor8       False          cytokine          86   52
17130                      _Treg_VEGF_Donor9_F1      CD4T         VEGF                      Treg_VEGF_Donor9_F1   F1                   Treg   Donor9       False          cytokine          79   38

[15257 rows x 11 columns]

In [11]:
ad.read_h5ad('/vol/projects/CIIM/perturbation_data/Parse_10M_PBMC_cytokines.h5ad', backed='r').obs

                          sample species  gene_count  tscp_count  mread_count  bc1_wind  bc2_wind  bc3_wind bc1_well bc2_well bc3_well  log1p_n_genes_by_counts  log1p_total_counts  total_counts_MT  pct_counts_MT  log1p_total_counts_MT    donor cytokine treatment              cell_type
89_103_005__s1    Donor10_4-1BBL    hg38        2236        4700         8656        89       103         5       H5    p2.A7       A5                 7.712891            8.455530             56.0       1.191490               4.043051  Donor10   4-1BBL  cytokine              CD8 Naive
89_103_083__s1    Donor10_4-1BBL    hg38        2222        4337         8235        89       103        83       H5    p2.A7      G11                 7.706613            8.375169             71.0       1.637076               4.276666  Donor10   4-1BBL  cytokine                B Naive
89_103_085__s1    Donor10_4-1BBL    hg38        1690        3079         5870        89       103        85       H5    p2.A7       H1                 7.433075            8.032685            197.0       6.398181               5.288267  Donor10   4-1BBL  cytokine  B Intermediate/Memory
89_104_009__s1    Donor10_4-1BBL    hg38        1746        3015         5663        89       104         9       H5    p2.A8       A9                 7.465655            8.011686             84.0       2.786070               4.442651  Donor10   4-1BBL  cytokine              CD14 Mono
89_104_025__s1    Donor10_4-1BBL    hg38        3182        6986        13153        89       104        25       H5    p2.A8       C1                 8.065579            8.851807            165.0       2.361867               5.111988  Donor10   4-1BBL  cytokine              CD14 Mono
...                          ...     ...         ...         ...          ...       ...       ...       ...      ...      ...      ...                      ...                 ...              ...            ...                    ...      ...      ...       ...                    ...
61_186_093__s144     Donor9_VEGF    hg38        1439        2381         4989        61       186        93       F1    p2.H6       H9                 7.272398            7.775696             43.0       1.805964               3.784190   Donor9     VEGF  cytokine             CD4 Memory
61_186_108__s144     Donor9_VEGF    hg38        1962        3457         7093        61       186       108       F1    p2.H6   p2.A12                 7.582229            8.148446             85.0       2.458779               4.454347   Donor9     VEGF  cytokine              CD14 Mono
61_186_135__s144     Donor9_VEGF    hg38        1589        2785         5983        61       186       135       F1    p2.H6    p2.D3                 7.371489            7.932362             49.0       1.759426               3.912023   Donor9     VEGF  cytokine              CD8 Naive
61_186_157__s144     Donor9_VEGF    hg38        1819        3342         7088        61       186       157       F1    p2.H6    p2.F1                 7.506592            8.114624             54.0       1.615799               4.007333   Donor9     VEGF  cytokine              CD8 Naive
61_186_168__s144     Donor9_VEGF    hg38        1628        2709         5704        61       186       168       F1    p2.H6   p2.F12                 7.396335            7.904704             44.0       1.624216               3.806663   Donor9     VEGF  cytokine  B Intermediate/Memory

[9697974 rows x 20 columns]